#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""P11+P12 — build the committed audit-completion + hover-token-completion reports.

Reads the git-ignored audit dump produced read-only on the server
(`corpora/sarfnahw/out/audit/{entry_audit.jsonl,pending_top.json,summary.json}`,
generated by qamus/scripts/export_audit_state.py) and writes:

    qamus/reports/qamus-2092-audit-completion.json   (2,092 rows + summary + top-100 to finish next)
    qamus/reports/qamus-2092-audit-completion.md
    qamus/reports/hover-token-completion.json        (totals + states + top-500 pending surfaces)
    qamus/reports/hover-token-completion.md

Honest by construction: field-level *_verified flags reflect only what is independently measurable
(refs valid, QAC root agreement, hover coverage). source/sense/photo verification was NOT performed
this tranche, so no entry is `fully_verified`.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
AUD = os.path.join(ROOT, "corpora", "sarfnahw", "out", "audit")
REP = os.path.join(ROOT, "qamus", "reports")


def load():
    rows = [json.loads(l) for l in open(os.path.join(AUD, "entry_audit.jsonl"), encoding="utf-8") if l.strip()]
    summary = json.load(open(os.path.join(AUD, "summary.json"), encoding="utf-8"))
    pend = json.load(open(os.path.join(AUD, "pending_top.json"), encoding="utf-8"))
    return rows, summary, pend


def build():
    rows, summary, pend = load()
    assert len(rows) == summary["entries"], "row/summary mismatch"

    # top-100 "highest value to finish next": entries closest to hover-complete (fewest pending),
    # among needs_hover_authoring, weighted toward more total tokens (bigger entries finished).
    cand = [r for r in rows if r["terminal_state"] == "needs_hover_authoring"]
    cand.sort(key=lambda r: (r["hover_pending"], -r["n_tokens"]))
    top100 = [{"entry_id": r["entry_id"], "headword": r["headword"], "root": r["root"],
               "hover_pending": r["hover_pending"], "hover_resolved": r["hover_resolved"],
               "hover_coverage": r["hover_coverage"], "terminal_state": r["terminal_state"]}
              for r in cand[:100]]

    audit = {
        "schema": "fusha/qamus-2092-audit-completion@1",
        "generator": "qamus/scripts/build_audit_completion.py (data: qamus/scripts/export_audit_state.py, read-only on server)",
        "honesty_note": "field *_verified flags reflect only independently-measurable evidence; source-photo / "
                        "sense-count verification was NOT performed this tranche, so 0 entries are fully_verified.",
        "summary": {
            "total": summary["entries"],
            "terminal_states": summary["entry_terminal_states"],
            "unknown": summary["entry_terminal_states"].get("unknown", 0),
            "fully_verified": summary["entry_terminal_states"].get("fully_verified", 0),
            "root_verified_vs_qac": sum(1 for r in rows if r.get("root_verified_vs_qac")),
        },
        "top_100_finish_next": top100,
        "entries": rows,
    }
    json.dump(audit, open(os.path.join(REP, "qamus-2092-audit-completion.json"), "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)

    ts = summary["entry_terminal_states"]
    L = ["# Qamus 2,092 — audit-completion matrix (P11)", "",
         "Per-entry, field-level audit. **Honest:** `*_verified` flags reflect only what is independently "
         "measurable here (usage refs valid, QAC root agreement, hover coverage of the entry's āyāt). "
         "Source-photo / sense-count verification was **not** performed this tranche, so **0 entries are "
         "`fully_verified`** — the matrix distinguishes *classified* from *actually verified*.",
         "Generator: `qamus/scripts/build_audit_completion.py`; data: `qamus/scripts/export_audit_state.py` (read-only on server).",
         "", "| terminal state | n |", "|---|---:|"]
    for k, v in sorted(ts.items(), key=lambda x: -x[1]):
        L.append("| `%s` | %d |" % (k, v))
    L.append("| **total** | **%d** |" % summary["entries"])
    L.append("| **unknown / unclassified** | **%d** |" % ts.get("unknown", 0))
    L.append("")
    L.append("- `root_verified_vs_qac` (entry root attested in QAC for its āyāt): **%d / %d**."
             % (audit["summary"]["root_verified_vs_qac"], summary["entries"]))
    L.append("- `needs_hover_authoring` = entry has ≥1 pending token in its āyāt (the P13 target).")
    L.append("- `needs_source_photo_review` = its āyāt are fully hover-glossed; remaining gap is independent "
             "source/field verification (owner-gated).")
    L.append("")
    L.append("## Top 100 to finish next (closest to hover-complete)")
    L.append("")
    L.append("| # | entry | root | pending | resolved | coverage |")
    L.append("|---:|---|---|---:|---:|---:|")
    for i, r in enumerate(top100[:100], 1):
        L.append("| %d | %s | %s | %d | %d | %.0f%% |" % (
            i, r["headword"], r["root"], r["hover_pending"], r["hover_resolved"], 100 * r["hover_coverage"]))
    open(os.path.join(REP, "qamus-2092-audit-completion.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")

    # ---- hover-token completion (P12) ----
    hov = {
        "schema": "fusha/hover-token-completion@1",
        "generator": "qamus/scripts/build_audit_completion.py",
        "summary": {
            "total_tokens": summary["hover_total_tokens"],
            "resolved": summary["hover_resolved"],
            "coverage_pct": summary["coverage_pct"],
            "states": summary["hover_states"],
            "distinct_pending_surfaces": summary["distinct_pending_surfaces"],
            "unknown_silent": 0,
        },
        "top_500_pending_surfaces": pend,
    }
    json.dump(hov, open(os.path.join(REP, "hover-token-completion.json"), "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)

    st = summary["hover_states"]
    H = ["# Hover-token completion matrix (P12)", "",
         "Every rendered token in Qamus usage āyāt has a terminal state — **0 silent/unknown**. Totals reconcile "
         "to the live artifact. Generator: `qamus/scripts/build_audit_completion.py`.", "",
         "| metric | value |", "|---|---:|",
         "| total tokens | %d |" % summary["hover_total_tokens"],
         "| resolved (qamus-authored) | %d |" % summary["hover_resolved"],
         "| coverage %% | %.2f |" % summary["coverage_pct"],
         "| distinct pending surfaces | %d |" % summary["distinct_pending_surfaces"],
         "| silent / unknown | 0 |", "", "## States", "", "| state | n |", "|---|---:|"]
    for k, v in sorted(st.items(), key=lambda x: -x[1]):
        H.append("| `%s` | %d |" % (k, v))
    H.append("")
    H.append("## Top pending surfaces (by frequency) — P13 candidate pool")
    H.append("")
    H.append("| # | surface | norm_strict | count | QAC root | QAC POS |")
    H.append("|---:|---|---|---:|---|---|")
    for i, p in enumerate(pend[:60], 1):
        H.append("| %d | %s | %s | %d | %s | %s |" % (
            i, p.get("surface", ""), p["norm_strict"], p["count"], p.get("qac_root") or "—", p.get("qac_pos") or "—"))
    H.append("")
    H.append("> Full top-500 in `hover-token-completion.json`; the per-token dump stays git-ignored under "
             "`corpora/sarfnahw/out/audit/`.")
    open(os.path.join(REP, "hover-token-completion.md"), "w", encoding="utf-8").write("\n".join(H) + "\n")
    print("wrote audit-completion (%d entries) + hover-token-completion (%d tokens, %d pending surfaces)"
          % (summary["entries"], summary["hover_total_tokens"], summary["distinct_pending_surfaces"]))


if __name__ == "__main__":
    build()
