#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Assemble the claude.ai Project Knowledge pack from the allowlist (dist/claude-ai/pack.include.txt).

Copies each approved repo file into dist/claude-ai/pack/ (preserving relative paths), regenerates
dist/claude-ai/knowledge-manifest.md, and enforces: only text files, no single file > 500 KB, total
< 5 MB, < 40 files, no banned path. Read-only over the repo except dist/claude-ai/pack/ + manifest.
"""
import hashlib, os, shutil, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, "dist", "claude-ai")
PACK = os.path.join(DIST, "pack")
INCLUDE = os.path.join(DIST, "pack.include.txt")
MAX_FILE = 500 * 1024
MAX_TOTAL = 5 * 1024 * 1024
MAX_FILES = 40
BANNED = ("entries.jsonl", "entries.min.jsonl", "indexes/current/", "candidates/", ".provenance.",
          "out/", "source_photo", "hover-token-audit-full.jsonl", "qamus-2092-entry-matrix.jsonl")

def norm_bytes(path):
    """Match the drift validator: compare text content, not checkout line endings."""
    text = open(path, encoding="utf-8").read().replace("\r\n", "\n").replace("\r", "\n")
    return text.encode("utf-8")

def main():
    paths = [l.strip() for l in open(INCLUDE, encoding="utf-8")
             if l.strip() and not l.lstrip().startswith("#")]
    if os.path.isdir(PACK):
        shutil.rmtree(PACK)
    os.makedirs(PACK, exist_ok=True)
    errors, manifest, total = [], [], 0
    for rel in paths:
        src = os.path.join(ROOT, rel)
        if any(b in rel for b in BANNED):
            errors.append("banned path in allowlist: %s" % rel); continue
        if not os.path.exists(src):
            errors.append("missing source: %s" % rel); continue
        normalized = norm_bytes(src)
        sz = len(normalized)
        if sz > MAX_FILE:
            errors.append("file > 500KB: %s (%d)" % (rel, sz)); continue
        total += sz
        dst = os.path.join(PACK, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)
        sha = hashlib.sha256(normalized).hexdigest()[:12]
        manifest.append((rel, sz, sha))
    if len(manifest) > MAX_FILES:
        errors.append("too many files: %d > %d" % (len(manifest), MAX_FILES))
    if total > MAX_TOTAL:
        errors.append("total too large: %d > %d" % (total, MAX_TOTAL))
    if errors:
        print("BUILD FAIL:"); [print("  -", e) for e in errors]; sys.exit(1)

    md = ["# claude.ai pack — knowledge manifest (generated by scripts/build_claude_ai_project_pack.py)", "",
          f"{len(manifest)} files · {total:,} bytes (cap: <40 files, <5 MB, no file >500 KB). Excludes the "
          "public dataset JSONL, all indexes/candidates/provenance/source-photo/out artifacts, and historical "
          "tranche reports.", "", "| file | bytes | sha256[:12] |", "|---|---:|---|"]
    for rel, sz, sha in manifest:
        md.append(f"| `{rel}` | {sz:,} | `{sha}` |")
    md.append("")
    open(os.path.join(DIST, "knowledge-manifest.md"), "w", encoding="utf-8", newline="\n").write("\n".join(md))
    print("PACK BUILT — %d files, %d bytes -> dist/claude-ai/pack/ ; manifest regenerated" % (len(manifest), total))

if __name__ == "__main__":
    main()
