#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Phase 6 — hover grammar-metadata audit. For every resolved token, record the metadata derivable from
the available evidence (root + coarse POS from QAC; token-decision id; segmentation; provenance) and flag
what is missing. Honest scope: gender/case/mood/derivative-class need a full morphological analyzer that
is NOT available offline, so those are flagged `*_metadata_missing` rather than fabricated. Read-only.
"""
import json, os, sys, collections
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import audit_all_hover_tokens as A
STAGE = os.path.join(ROOT, "out", "hover_stage")
OUTDIR = os.path.join(ROOT, "qamus", "reports", "closure-2092")

def main():
    wbw = json.load(open(os.path.join(STAGE, "wbw-lookup.json"), encoding="utf-8"))
    words, verses = wbw["words"], wbw["verses"]
    dec = {}
    for l in open(os.path.join(STAGE, "fusha-hover-token-decisions.jsonl"), encoding="utf-8"):
        l = l.strip()
        if l:
            d = json.loads(l); dec[d["loc"]] = d
    roots = {}
    for l in open(os.path.join(STAGE, "qac-roots.tsv"), encoding="utf-8"):
        p = l.rstrip("\n").split("\t")
        if len(p) >= 2: roots[p[0]] = p[1]
    pos = {}
    for l in open(os.path.join(STAGE, "qac-tokroots.tsv"), encoding="utf-8"):
        p = l.rstrip("\n").split("\t")
        if len(p) >= 4: pos[(p[0], A.norm_strict(p[1]))] = p[3].strip()

    rows = []
    cov = collections.Counter()
    for loc, tok in words.items():
        sa = ":".join(loc.split(":")[:2]); nk = A.norm_strict(tok.get("ar", ""))
        r = roots.get(loc); pp = pos.get((sa, nk))
        td = dec.get(loc)
        has_root = bool(r); has_pos = bool(pp)
        seg = bool(td and (td.get("stem") or td.get("suffix")))  # explicit clitic segmentation present
        cov["root_derivable"] += has_root; cov["pos_derivable"] += has_pos
        cov["token_decision"] += bool(td)
        if pp == "P":
            cov["particle"] += 1
            if td: cov["particle_function_present"] += 1
        rows.append({"loc": loc, "surface": tok.get("ar"), "nk": nk,
                     "root": r, "pos": pp, "token_decision": bool(td),
                     "segmentation": seg, "conf": tok.get("conf"),
                     "provenance_clean": (tok.get("glosses", [{}])[0].get("src") == "qamus")})
    total = len(rows)
    summ = {"_generator": "tools/audit_hover_grammar_metadata.py", "resolved": total,
            "root_derivable": cov["root_derivable"], "root_derivable_pct": round(100*cov["root_derivable"]/total, 2),
            "pos_derivable": cov["pos_derivable"], "pos_derivable_pct": round(100*cov["pos_derivable"]/total, 2),
            "with_token_decision": cov["token_decision"],
            "particles": cov["particle"], "particles_with_function_decision": cov["particle_function_present"],
            "note": "gender/number/case/mood/derivative-class require a morphological analyzer not available offline; "
                    "flagged missing, never fabricated. The concise PUBLIC gloss may be correct even when internal "
                    "metadata is incomplete."}
    with open(os.path.join(OUTDIR, "hover-grammar-metadata-audit-20260624.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(summ, f, ensure_ascii=False, sort_keys=True, indent=2); f.write("\n")
    with open(os.path.join(OUTDIR, "hover-grammar-metadata-audit-20260624.jsonl"), "w", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(summ, ensure_ascii=False) + "\n")
        for r in rows[:5000]:   # sample (full set is regenerable); summary covers all
            f.write(json.dumps(r, ensure_ascii=False, sort_keys=True) + "\n")
    md = ["# Hover grammar-metadata audit (closure-2092 Phase 6)", "",
          "Generated by `tools/audit_hover_grammar_metadata.py`. Per-token derivable metadata over all "
          f"**{total:,}** resolved tokens. Honest scope: gender/number/case/mood/derivative-class need a "
          "morphological analyzer not available offline — flagged missing, never fabricated.", "",
          "| metadata | coverage |", "|---|---|",
          f"| root derivable (QAC) | {summ['root_derivable']:,} ({summ['root_derivable_pct']}%) |",
          f"| POS derivable (QAC, coarse N/P/V) | {summ['pos_derivable']:,} ({summ['pos_derivable_pct']}%) |",
          f"| carries a per-loc token decision | {summ['with_token_decision']:,} |",
          f"| particles | {summ['particles']:,} ({summ['particles_with_function_decision']:,} with an explicit function decision) |",
          "", "Companion quality audit: `hover-gloss-quality-audit.*` (91.20% clean, 0 public source leaks). "
          "Repair queues = too_generic_gloss / particle_function_missing / homograph_reason_missing (internal "
          "metadata enrichment; the concise public display is not auto-rewritten).", ""]
    open(os.path.join(OUTDIR, "hover-grammar-metadata-audit-20260624.md"), "w", encoding="utf-8", newline="\n").write("\n".join(md))
    print("GRAMMAR-METADATA AUDIT OK — root %d%% / POS %d%% derivable; particles %d (%d with function)"
          % (summ["root_derivable_pct"], summ["pos_derivable_pct"], summ["particles"], summ["particles_with_function_decision"]))

if __name__ == "__main__":
    main()
