#!/usr/bin/env python3
"""Build the Phase 3.25 GrammarProblems regression-mining ledger.

This does not re-copy the source PDF questions. It groups the existing
GrammarProblems-derived eval rows into small mining batches and assigns each
case to the Phase 3.25 issue buckets requested before Phase 4 authoring.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from validate_grammar_regression_mining import (
    DEFAULT_EVAL,
    DEFAULT_LEDGER,
    load_jsonl,
    validate_rows,
)


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "nahw" / "evals" / "grammar-problems-phase3p25-mining.md"
BATCH_SIZE = 12

ISSUE_1 = "Issue #1 - right answer with wrong i'rab/reasoning is unsafe"
ISSUE_2 = "Issue #2 - function, attachment, and role ambiguity"
ISSUE_3 = "Issue #3 - morphosyntax and visible-token preservation"
POSITIVE = "Positive regression control - direct case remains gated but not over-escalated"

ISSUE_2_TOPICS = {
    "badal",
    "hal",
    "idafa",
    "ikhtisas",
    "istithna",
    "jar_majrur",
    "maful_li_ajlih",
    "maful_mutlaq",
    "mubtada_khabar",
    "tamyiz",
    "tanazu",
}


def classify(row: dict) -> tuple[str, str, str, str, bool]:
    topic = row.get("topic")
    gate = row.get("required_gate")
    bloom = row.get("bloom")
    depth = row.get("depth")
    fmt = row.get("format")

    if gate == "auto_safe":
        return (
            "correct_positive_regression",
            POSITIVE,
            "phase3p25_positive_control",
            "keep as a positive control; auto-safe remains conditional on source-address and sarf/nahw gates",
            False,
        )

    if row.get("wrong_reasoning_trap") or depth == "deep" or fmt == "essay" or bloom in {
        "analysis",
        "evaluation",
        "generation",
    }:
        return (
            "already_covered_issue_1",
            ISSUE_1,
            "phase3p25_batch_ready",
            "exercise the answer-plus-reasoning gate; a correct final answer with wrong reasoning must still fail",
            False,
        )

    if topic in ISSUE_2_TOPICS:
        return (
            "already_covered_issue_2",
            ISSUE_2,
            "phase3p25_batch_ready",
            "exercise the function or attachment gate before any hover decision can propagate",
            False,
        )

    return (
        "already_covered_issue_3",
        ISSUE_3,
        "phase3p25_batch_ready",
        "exercise morphology, case, mood, voice, or visible-token preservation before any hover decision can propagate",
        False,
    )


def build_rows(eval_rows: list[dict]) -> list[dict]:
    out: list[dict] = []
    for i, row in enumerate(eval_rows):
        batch_index = (i // BATCH_SIZE) + 1
        case_index = (i % BATCH_SIZE) + 1
        classification, cluster, status, next_action, needs_new = classify(row)
        out.append(
            {
                "phase": "3.25",
                "source_eval_id": row["id"],
                "batch_id": f"GP25-B{batch_index:03d}",
                "batch_index": batch_index,
                "case_index": case_index,
                "level": row.get("level"),
                "bloom": row.get("bloom"),
                "format": row.get("format"),
                "depth": row.get("depth"),
                "topic": row.get("topic"),
                "required_gate": row.get("required_gate"),
                "classification": classification,
                "issue_cluster": cluster,
                "status": status,
                "next_action": next_action,
                "needs_new_issue": needs_new,
            }
        )
    return out


def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def write_report(path: Path, rows: list[dict]) -> None:
    counts = Counter(row["classification"] for row in rows)
    topics = Counter(row["topic"] for row in rows)
    batches = Counter(row["batch_id"] for row in rows)
    lines = [
        "# GrammarProblems Phase 3.25 regression-mining ledger",
        "",
        "Generated by `tools/build_grammar_regression_mining.py` from",
        "`nahw/evals/grammar-problems-derived-eval.jsonl`.",
        "",
        "This is a control ledger for the pre-Phase-4 regression-mining sweep. It",
        "does not copy the PDF questions/answers and does not claim a fresh model",
        "grading run. It forces every existing executable GrammarProblems case into",
        "a small batch and one of the Phase 3.25 disposition buckets.",
        "",
        "## Issue buckets",
        "",
        f"- **Issue #1:** {ISSUE_1}",
        f"- **Issue #2:** {ISSUE_2}",
        f"- **Issue #3:** {ISSUE_3}",
        "- **New root-cause cluster:** no rows yet; validator requires a proposed issue id if one appears.",
        "- **Correct positive regression:** direct cases that should remain safe only under existing gates.",
        "",
        "## Counts",
        "",
        f"- total rows: {len(rows)}",
        f"- batches: {len(batches)} (max batch size {max(batches.values()) if batches else 0})",
        "",
        "| classification | rows |",
        "|---|---:|",
    ]
    for key in sorted(counts):
        lines.append(f"| `{key}` | {counts[key]} |")
    lines.extend(["", "## Topic counts", "", "| topic | rows |", "|---|---:|"])
    for key in sorted(topics):
        lines.append(f"| `{key}` | {topics[key]} |")
    lines.extend(
        [
            "",
            "## Phase 3.25 operating rule",
            "",
            "Each batch can now be run as a bounded regression-mining sweep. Results",
            "must update the ledger only by moving a row to `new_root_cause_cluster`",
            "with a proposed issue id, or by keeping it in one of the already-covered",
            "buckets with concrete evidence. Phase 4 corpus-facing grammar authoring",
            "must not start from an unclassified GrammarProblems row.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def run_self_test() -> None:
    fixture = [
        {"id": "GP-T-001", "required_gate": "auto_safe", "topic": "jar_majrur", "bloom": "recall", "depth": "direct", "format": "objective", "level": "ajurrumiyyah"},
        {"id": "GP-T-002", "required_gate": "two_vote_required", "topic": "signs_of_irab", "bloom": "analysis", "depth": "deep", "format": "essay", "level": "qatr_al_nada"},
        {"id": "GP-T-003", "required_gate": "two_vote_required", "topic": "idafa", "bloom": "application", "depth": "direct", "format": "objective", "level": "awdah_al_masalik"},
        {"id": "GP-T-004", "required_gate": "two_vote_required", "topic": "building_present_verb", "bloom": "understanding", "depth": "direct", "format": "objective", "level": "ajurrumiyyah"},
    ]
    rows = build_rows(fixture)
    ok, errors, counts = validate_rows(rows, [r["id"] for r in fixture])
    assert ok, errors
    assert counts["classification:correct_positive_regression"] == 1
    assert counts["classification:already_covered_issue_1"] == 1
    assert counts["classification:already_covered_issue_2"] == 1
    assert counts["classification:already_covered_issue_3"] == 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--eval", default=str(DEFAULT_EVAL))
    parser.add_argument("--out", default=str(DEFAULT_LEDGER))
    parser.add_argument("--report", default=str(DEFAULT_REPORT))
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        run_self_test()
        print("build_grammar_regression_mining self-test OK")
        return 0

    eval_path = Path(args.eval)
    rows = build_rows(load_jsonl(eval_path))
    ok, errors, _ = validate_rows(rows, [r["id"] for r in load_jsonl(eval_path)])
    if not ok:
        for error in errors:
            print(f"- {error}")
        return 1
    write_jsonl(Path(args.out), rows)
    write_report(Path(args.report), rows)
    print(f"Wrote {len(rows)} rows to {args.out}")
    print(f"Wrote report to {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
