#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate docs/current-state.yaml — the machine-readable programme state.

Continuation-machinery lane (owner handoff steer section 12).  Every number in
docs/current-state.yaml is COMPUTED from committed artifacts by this script,
never hand-edited, so the file cannot hand-rot.  Counts that exist only in
owner packets (outside this repo) are carried in a clearly separated
``reported_not_in_repo`` block.

The ``generated_from_commit`` field records the HEAD at generation time and is
EXCLUDED from staleness comparison (``--check``), because the commit that adds
the file necessarily changes HEAD.  Verify the repo state itself with:
  git rev-parse HEAD && python tools/check_regressions.py

Usage:
  python tools/build_current_state.py            # rewrite docs/current-state.yaml
  python tools/build_current_state.py --check    # fail if committed copy is stale
"""

from __future__ import annotations

import argparse
import io
import json
import os
import subprocess
import sys
from collections import Counter

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "current-state.yaml")

ENTRIES = os.path.join(ROOT, "qamus", "data", "current", "entries.jsonl")
UNIVERSE_META = os.path.join(ROOT, "qamus", "lattice",
                             "example-ayah-universe.meta.json")
P007_META = os.path.join(ROOT, "qamus", "lattice",
                         "p007-reverse-universe.meta.json")
PILOT_EVENTS = os.path.join(ROOT, "qamus", "examples", "p007-li-pilot",
                            "certification", "events.jsonl")
GEOM_EVENTS = os.path.join(ROOT, "qamus", "certification",
                           "p007-geometry-wave", "events.jsonl")
ROLLOUT_META = os.path.join(ROOT, "qamus", "reports",
                            "pvn-rollout-map.meta.json")
NEXT_ACTIONS = os.path.join(ROOT, "qamus", "work-queues",
                            "next-actions.jsonl")


def _certified(events_path):
    st = {}
    with io.open(events_path, encoding="utf-8") as fh:
        for line in fh:
            r = json.loads(line)
            st[r["fact_id"]] = r["to_status"]
    return sum(1 for v in st.values() if v == "certified")


def _head():
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                              capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:
        return "UNKNOWN"


def build_yaml(head):
    sections = Counter()
    with io.open(ENTRIES, encoding="utf-8") as fh:
        for line in fh:
            sections[json.loads(line).get("section")] += 1
    with io.open(UNIVERSE_META, encoding="utf-8") as fh:
        um = json.load(fh)
    with io.open(P007_META, encoding="utf-8") as fh:
        pm = json.load(fh)
    tallies = pm["state_tallies"]
    pilot = _certified(PILOT_EVENTS)
    geom = _certified(GEOM_EVENTS)
    with io.open(ROLLOUT_META, encoding="utf-8") as fh:
        rollout_rows = json.load(fh)["rows"]
    next_actions = 0
    if os.path.exists(NEXT_ACTIONS):
        with io.open(NEXT_ACTIONS, encoding="utf-8") as fh:
            next_actions = sum(1 for l in fh if l.strip())
    uni_tot = um.get("totals") or {}

    lines = [
        "# docs/current-state.yaml — machine-readable programme state.",
        "# GENERATED by tools/build_current_state.py — NEVER hand-edit.",
        "# Regenerate: python tools/build_current_state.py",
        "# Staleness gate: python tools/build_current_state.py --check "
        "(wired into tools/check_regressions.py)",
        "schema: qamus.current_state.v1",
        "generated_from_commit: %s  # excluded from --check comparison" % head,
        "verify_head: git rev-parse HEAD && python tools/check_regressions.py",
        "mode: candidate — no live mutation from this repo, ever",
        "entries:",
        "  total: %d" % sum(sections.values()),
        "  verb: %d" % sections["verb"],
        "  noun: %d" % sections["noun"],
        "  particle: %d" % sections["particle"],
        "example_ayah_universe:  # qamus/lattice/example-ayah-universe.meta.json",
    ]
    for k in sorted(uni_tot):
        lines.append("  %s: %s" % (k, uni_tot[k]))
    lines += [
        "certified_typed_facts:",
        "  warning: facts != occurrences != entries != appearances — four "
        "different denominators, never conflate",
        "  in_repo_event_verified:  # recomputed from hash-chained event trails",
        "    p007_pilot_entry_sense_function_governor: %d" % pilot,
        "    p007_geometry_wave_mechanical_only: %d" % geom,
        "    subtotal: %d" % (pilot + geom),
        "  reported_not_in_repo:  # owner-packet lanes, not yet committed here",
        "    p007_direct_source_w1_function: 520",
        "    p007_two_vote_w1: 126",
        "  reported_programme_total_approx: 2057",
        "p007_reverse_universe:  # qamus/lattice/p007-reverse-universe.meta.json",
        "  rows: %d" % pm["rows"],
        "  appearances_total: %d" % pm["appearances_total"],
        "  queues:",
        "    direct_source_function_queue: %d"
        % tallies["P007_DIRECT_SOURCE_FUNCTION_QUEUE"]["rows"],
        "    two_vote_queue: %d" % tallies["P007_TWO_VOTE_QUEUE"]["rows"],
        "    scholar_queue: %d" % tallies["P007_SCHOLAR_QUEUE"]["rows"],
        "    rejected_closed: %d" % tallies["P007_REJECTED_CLOSED"]["rows"],
        "  entry_links_certified: %d"
        % tallies["P007_ENTRY_LINKS_CERTIFIED"]["rows"],
        "rollout_map:",
        "  rows: %d" % rollout_rows,
        "  file: qamus/reports/pvn-rollout-map.jsonl",
        "  regenerate: python tools/build_pvn_rollout_map.py",
        "work_queues:",
        "  next_actions_rows: %d" % next_actions,
        "  file: qamus/work-queues/next-actions.jsonl",
        "blockers: docs/blockers.yaml",
        "entry_point: START-HERE-FOR-CONTINUATION.md",
        "golden_commands: docs/golden-commands.md",
        "model_routing: docs/model-routing-guide.md",
        "decision_ledger: docs/decision-ledger.md",
        "",
    ]
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    text = build_yaml(_head())
    if args.check:
        if not os.path.exists(OUT):
            print("STALE: docs/current-state.yaml missing")
            return 1
        with io.open(OUT, encoding="utf-8") as fh:
            committed = fh.read()

        def strip_head(t):
            return "\n".join(l for l in t.splitlines()
                             if not l.startswith("generated_from_commit:"))
        if strip_head(committed) != strip_head(text):
            print("STALE: docs/current-state.yaml differs from regeneration")
            return 1
        print("CURRENT STATE FRESH")
        return 0
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote " + OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
