#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build a public-clean hover decision batch from deterministic triangulation rows."""
import argparse
import collections
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_TABLE = os.path.join(ROOT, "qamus", "reports", "closure-2092",
                             "pending-source-triangulation-table.jsonl")
DEFAULT_OUT = os.path.join(ROOT, "qamus", "candidates", "qamus_2092",
                           "bulk_deterministic_hover_batch_001.jsonl")
DEFAULT_PROV = os.path.join(ROOT, "qamus", "candidates", "qamus_2092",
                            "bulk_deterministic_hover_batch_001.provenance.jsonl")
DEFAULT_REPORT_JSON = os.path.join(ROOT, "qamus", "reports", "closure-2092",
                                   "bulk-deterministic-batch-001.json")
DEFAULT_REPORT_MD = os.path.join(ROOT, "qamus", "reports", "closure-2092",
                                 "bulk-deterministic-batch-001.md")

LEAK_RE = re.compile(r"\b(qac|quran\.com|quran-com|corpus\.quran|quranic arabic corpus|"
                     r"tanzil|saheeh|sahih|tafsir|ocr)\b", re.I)


def read_jsonl(path):
    return [json.loads(line) for line in open(path, encoding="utf-8") if line.strip()]


def write_jsonl(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def eligible(row):
    return (
        row.get("deterministic_resolvable") is True
        and row.get("gate") == "auto_rule"
        and row.get("suggested_lane") == "auto_resolve_deterministic"
        and row.get("public_payload_allowed") == "yes"
        and row.get("public_provenance_clean") is True
        and row.get("pos_agreement") == "agree"
        and row.get("proposed_gloss")
        and not LEAK_RE.search(row.get("proposed_gloss") or "")
    )


def build_batch(table_path=DEFAULT_TABLE, out_path=DEFAULT_OUT, provenance_path=DEFAULT_PROV,
                report_json_path=None, report_md_path=None):
    table = read_jsonl(table_path)
    public_rows = []
    provenance_rows = []
    skipped = collections.Counter()

    for row in table:
        if not row.get("deterministic_resolvable"):
            skipped["not_deterministic"] += 1
            continue
        if not eligible(row):
            skipped["failed_auto_contract"] += 1
            continue
        loc = row["loc"]
        public_rows.append({
            "loc": loc,
            "gloss": row["proposed_gloss"].strip(),
            "surface": row.get("surface_ar") or "",
            "key": row.get("strict_nk") or row.get("nk") or "",
            "state_id": "state:tok:%s" % loc,
            "src": "qamus",
            "kind": "authored",
            "lang": "en",
            "decision_state": "bulk_deterministic_auto_rule",
        })
        provenance_rows.append({
            "loc": loc,
            "surface": row.get("surface_ar") or "",
            "key": row.get("strict_nk") or row.get("nk") or "",
            "gloss": row["proposed_gloss"].strip(),
            "review_status": "auto_rule_certified",
            "votes": 0,
            "gate": "auto_rule",
            "deterministic_reason": row.get("deterministic_reason"),
            "qamus_entry_candidate": row.get("qamus_entry_candidate"),
            "qamus_entry_headword": row.get("qamus_entry_headword"),
            "qamus_entry_match_type": row.get("qamus_entry_match_type"),
            "qac_root": row.get("qac_root"),
            "qac_pos": row.get("qac_pos"),
            "pos_agreement": row.get("pos_agreement"),
            "public_provenance_clean": True,
            "source_table": os.path.relpath(table_path, ROOT),
        })

    write_jsonl(out_path, public_rows)
    write_jsonl(provenance_path, provenance_rows)

    summary = {
        "_generator": "tools/build_bulk_deterministic_hover_decisions.py",
        "source_table": os.path.relpath(table_path, ROOT),
        "batch": os.path.relpath(out_path, ROOT),
        "provenance": os.path.relpath(provenance_path, ROOT),
        "rows": len(public_rows),
        "skipped": dict(skipped),
    }
    if report_json_path:
        os.makedirs(os.path.dirname(report_json_path), exist_ok=True)
        with open(report_json_path, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(summary, handle, ensure_ascii=False, indent=2, sort_keys=True)
            handle.write("\n")
    if report_md_path:
        os.makedirs(os.path.dirname(report_md_path), exist_ok=True)
        lines = [
            "# Bulk deterministic hover batch 001",
            "",
            "Generated by `tools/build_bulk_deterministic_hover_decisions.py` from the validated pending source-triangulation table.",
            "",
            "| metric | value |",
            "|---|---:|",
            "| public rows | %d |" % len(public_rows),
        ]
        for key, value in sorted(skipped.items()):
            lines.append("| skipped:%s | %d |" % (key, value))
        with open(report_md_path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("\n".join(lines) + "\n")
    return summary


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--from-table", default=DEFAULT_TABLE)
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--provenance", default=DEFAULT_PROV)
    parser.add_argument("--report-json", default=DEFAULT_REPORT_JSON)
    parser.add_argument("--report-md", default=DEFAULT_REPORT_MD)
    args = parser.parse_args()
    summary = build_batch(args.from_table, args.out, args.provenance, args.report_json, args.report_md)
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
