#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Report-ergonomics gate — the Markdown counterpart to check_artifact_ergonomics.py (which fixed
mega-JSON). Fails reviewer-facing Markdown reports that are effectively one-line mega-reports or have
crushed tables. Deliberately NOT overzealous: it only flags the two failure modes that make a report
un-dogfoodable, plus a soft warning for generated reports lacking a generator note.

Scope: committed *.md under qamus/reports/. Exit non-zero on any hard failure.
"""
import os, re, sys, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCOPE = os.path.join("qamus", "reports")

def tracked_md():
    try:
        out = subprocess.check_output(["git", "-C", ROOT, "ls-files", SCOPE + "/*.md"],
                                      text=True, encoding="utf-8")
        return [p for p in out.splitlines() if p.endswith(".md")]
    except Exception:
        res = []
        for dp, _, fs in os.walk(os.path.join(ROOT, SCOPE)):
            for f in fs:
                if f.endswith(".md"):
                    res.append(os.path.relpath(os.path.join(dp, f), ROOT).replace("\\", "/"))
        return res

def main():
    fails, warns = [], []
    for rel in tracked_md():
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p): continue
        txt = open(p, encoding="utf-8").read()
        nbytes = len(txt.encode("utf-8"))
        lines = txt.splitlines()
        nlines = len(lines)

        # 1) crushed one-line mega-report: lots of content, almost no line breaks
        if nbytes > 1500 and nlines < 6:
            fails.append(f"{rel}: {nbytes} bytes in {nlines} lines — crushed one-line report "
                         "(put headings/paragraphs on separate lines)")
            continue

        # 2) table crushed onto one physical line: a '|' cell-rich line with no sibling table rows
        pipe_lines = [ln for ln in lines if ln.count("|") >= 3]
        if pipe_lines:
            longest = max(pipe_lines, key=len)
            if longest.count("|") >= 8 and len(pipe_lines) < 2:
                fails.append(f"{rel}: a table appears crushed onto one line "
                             "(each row needs its own line)")

        # 3) must have at least one ATX heading on its own line
        if nbytes > 400 and not any(re.match(r"^#{1,6}\s+\S", ln) for ln in lines):
            warns.append(f"{rel}: no Markdown heading found (add a '# Title')")

        # 4) soft: generated reports should name their generator/source
        low = txt.lower()
        if ("generated by" not in low and "_generator" not in low
                and re.search(r"\b(scoreboard|ledger|audit|matrix|rollup)\b", rel.lower())):
            warns.append(f"{rel}: generated-style report without a generator/source note")

    for w in warns:
        print("warn:", w)
    if fails:
        print("\nREPORT ERGONOMICS FAIL:")
        for f in fails:
            print("  -", f)
        sys.exit(1)
    print(f"REPORT ERGONOMICS OK — {len(tracked_md())} reports reviewable ({len(warns)} soft warnings)")

if __name__ == "__main__":
    main()
