#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Classify every committed JSON/JSONL artifact into the ergonomics taxonomy → reviewer report.

Writes qamus/reports/artifact-taxonomy.md (human) + a per-file table. Uses the same classify()
as tools/check_artifact_ergonomics.py (single source of truth).
"""
import io, json, os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from check_artifact_ergonomics import classify, ROOT

CLASS_DESC = {
    "canonical-machine": "JSONL row-records (1 JSON object/line) — machine-read, line-diffable",
    "reviewer-facing": "pretty JSON (indent=2, sort_keys, ensure_ascii=False, trailing newline)",
    "compact-checksum": "compact single-line allowed (*.min.json / checksums.json)",
    "sample": "small illustrative *.sample.* artifact",
    "source-boundary": "provenance / source-adapter boundary doc",
    "generated-cache": "machine cache — should be gitignored",
}

def main():
    files = [l for l in subprocess.run(["git","ls-files","*.json","*.jsonl"], cwd=ROOT,
             capture_output=True, text=True).stdout.splitlines() if l.strip()]
    by_cls = {}
    rows = []
    for rel in sorted(files):
        cls = classify(rel)
        by_cls.setdefault(cls, []).append(rel)
        p = os.path.join(ROOT, rel)
        nbytes = os.path.getsize(p) if os.path.exists(p) else 0
        rows.append((rel, cls, nbytes))
    md = ["# Artifact taxonomy\n",
          "Every committed JSON/JSONL artifact and its ergonomics class. Generated by "
          "`tools/classify_artifacts.py`; enforced by `tools/check_artifact_ergonomics.py`.\n",
          "## Classes\n", "| class | rule | count |", "|---|---|---:|"]
    for cls in sorted(by_cls):
        md.append(f"| `{cls}` | {CLASS_DESC.get(cls,'')} | {len(by_cls[cls])} |")
    md.append("\n## Files\n| file | class | bytes |\n|---|---|---:|")
    for rel, cls, nb in sorted(rows, key=lambda r: (r[1], r[0])):
        md.append(f"| `{rel}` | {cls} | {nb:,} |")
    out = os.path.join(ROOT, "qamus", "reports", "artifact-taxonomy.md")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(md) + "\n")
    print("classes:", {k: len(v) for k, v in sorted(by_cls.items())})
    print("wrote", os.path.relpath(out, ROOT))

if __name__ == "__main__":
    main()
