#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""validate_claude_ai_pack_drift — READ-ONLY drift guard for the claude.ai knowledge pack manifest.

scripts/build_claude_ai_project_pack.py copies an allowlist of repo files into dist/claude-ai/pack/ and writes
dist/claude-ai/knowledge-manifest.md, recording per-file `bytes` + `sha256[:12]` of each SOURCE file. That manifest
can silently go stale: another lane edits a source file (sarf/SKILL.md, README.md, …) without rebuilding the pack,
and the published manifest no longer matches what would ship. scripts/verify_claude_ai_pack.py MUTATES (it rebuilds
the pack when absent), so it is unfit as a pure read-only drift sentinel.

This tool re-parses the manifest table and, for EVERY listed file, recomputes `sha256(ROOT/<rel>)[:12]` (and bytes)
from the SOURCE and compares to the recorded value. It FAILs on:
  * SHA drift (source content changed since the manifest was generated);
  * byte-size drift (defensive: catches a same-prefix-collision-resistant size change);
  * a manifest row whose source file no longer exists.
It is strictly READ-ONLY — it never rebuilds the pack or writes the manifest (that is the build script's job).

`--self-test` runs on a SYNTHETIC manifest+files (a matching pair must pass; a drifted/missing pair must be caught)
and NEVER fails on the real (possibly stale) committed manifest — so it is safe to wire into the regression gate.
`--real` reports drift against the committed manifest for humans (exit non-zero on drift) but the gate uses only
`--self-test`, because the manifest is regenerated by the build script and may legitimately lag source edits until
the next rebuild. All emitted text is leak-scanned via tools.leak_sot before printing.

Stdlib only. No network, no writes. CLI: [manifest.md] | --real | --self-test.
See parserplans/fusha-data-runtime-completion-pass (P2-10).
"""
import argparse
import hashlib
import os
import re
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

try:
    from tools import leak_sot as _LEAK
except ImportError:  # allow `python tools/validate_claude_ai_pack_drift.py` from the repo root
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from tools import leak_sot as _LEAK

_REPO = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
_MANIFEST = os.path.join(_REPO, "dist", "claude-ai", "knowledge-manifest.md")
_SHA_LEN = 12

# manifest table row: | `<rel/path>` | <bytes-with-commas> | `<sha256[:12]>` |
_ROW = re.compile(r"^\|\s*`([^`]+)`\s*\|\s*([\d,]+)\s*\|\s*`([0-9a-fA-F]+)`\s*\|\s*$", re.M)


def parse_manifest(manifest_path):
    """Return [(rel, bytes:int, sha12:str)] for every data row in the manifest table (header rows are skipped)."""
    text = open(manifest_path, encoding="utf-8").read()
    rows = []
    for rel, size, sha in _ROW.findall(text):
        rows.append((rel.strip(), int(size.replace(",", "")), sha.lower()))
    return rows


def _norm_bytes(path):
    """Line-ending-normalized UTF-8 bytes of a text file (\\r\\n and lone \\r -> \\n). Drift is checked on CONTENT, not
    raw bytes, so a CRLF working-tree checkout (Windows core.autocrlf) does not false-positive against the LF-based
    manifest. The manifest is generated from LF source, so a normalized read matches in BOTH LF and CRLF checkouts."""
    txt = open(path, encoding="utf-8").read().replace("\r\n", "\n").replace("\r", "\n")
    return txt.encode("utf-8")


def _sha12(path):
    return hashlib.sha256(_norm_bytes(path)).hexdigest()[:_SHA_LEN]


def check(manifest_path=_MANIFEST, repo_root=_REPO):
    """Reconcile the manifest against the SOURCE files. Returns (rows_checked, [drift-message, ...])."""
    drifts = []
    rows = parse_manifest(manifest_path)
    if not rows:
        return 0, ["manifest has no parseable table rows: %s" % manifest_path]
    for rel, want_sz, want_sha in rows:
        src = os.path.join(repo_root, rel)
        if not os.path.exists(src):
            drifts.append("missing source for manifest row: %s" % rel)
            continue
        got_sha = _sha12(src)
        got_sz = len(_norm_bytes(src))   # line-ending-normalized size (matches the LF-based manifest in any checkout)
        if got_sha != want_sha:
            drifts.append("sha drift %s: manifest %s but source %s" % (rel, want_sha, got_sha))
        if got_sz != want_sz:
            drifts.append("byte drift %s: manifest %d but source %d" % (rel, want_sz, got_sz))
    return len(rows), drifts


def _emit(line):
    """Print a line only after leak-scanning it (paths are repo-relative, but stay honest by construction)."""
    if _LEAK.is_leak(line):
        line = _LEAK.redact(line)
    print(line)


def _self_test():
    import json  # noqa: F401  (kept for parity; not used — manifest is markdown, not json)
    import tempfile
    failures = []

    def write(d, rel, body):
        p = os.path.join(d, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(body)
        return p

    def manifest_for(d, entries):
        """Build a manifest exactly like build_claude_ai_project_pack.py would, from on-disk sources."""
        lines = ["# claude.ai pack — knowledge manifest", "", "| file | bytes | sha256[:12] |", "|---|---:|---|"]
        for rel in entries:
            src = os.path.join(d, rel)
            lines.append("| `%s` | %s | `%s` |" % (rel, format(os.path.getsize(src), ","), _sha12(src)))
        return "\n".join(lines) + "\n"

    with tempfile.TemporaryDirectory() as d:
        write(d, "README.md", "hello pack\n")
        write(d, "sub/dir/SKILL.md", "skill body line one\nline two\n")
        mpath = write(d, "manifest.md", manifest_for(d, ["README.md", "sub/dir/SKILL.md"]))

        # 1) clean manifest -> no drift, both rows checked
        n, dr = check(mpath, d)
        if n != 2:
            failures.append("expected 2 rows checked, got %d" % n)
        if dr:
            failures.append("a matching manifest should report no drift: %s" % dr)

        # 2) edit a source after the manifest was written -> sha AND byte drift caught for that file only
        write(d, "README.md", "hello pack — EDITED so the hash changes\n")
        n, dr = check(mpath, d)
        if not any("sha drift README.md" in x for x in dr):
            failures.append("sha drift on an edited source was not caught: %s" % dr)
        if not any("byte drift README.md" in x for x in dr):
            failures.append("byte drift on an edited source was not caught: %s" % dr)
        if any("SKILL.md" in x for x in dr):
            failures.append("an unedited file was wrongly flagged: %s" % dr)

        # 3) a manifest row whose source vanished -> missing-source drift caught
        os.remove(os.path.join(d, "sub/dir/SKILL.md"))
        n, dr = check(mpath, d)
        if not any("missing source" in x and "SKILL.md" in x for x in dr):
            failures.append("a vanished source was not caught: %s" % dr)

    with tempfile.TemporaryDirectory() as d:
        # 4) a manifest with no parseable table rows is a defect, not a silent pass
        mpath = write(d, "empty.md", "# no table here\n\njust prose\n")
        n, dr = check(mpath, d)
        if n != 0 or not any("no parseable table rows" in x for x in dr):
            failures.append("an empty/parseless manifest should be flagged: %d / %s" % (n, dr))

    # 5) the real manifest must PARSE (>=1 row); staleness vs sources is reported, NOT a self-test failure
    #    (the build script regenerates it; this gate must never go red just because a lane edited a source).
    if os.path.exists(_MANIFEST):
        real_rows = parse_manifest(_MANIFEST)
        if not real_rows:
            failures.append("real manifest did not parse into table rows")

    for f in failures:
        _emit("FAIL " + f)
    if not failures:
        _emit("ok   validate_claude_ai_pack_drift self-test: matching manifest passes; sha/byte/missing-source/"
              "unparseable drift all caught; real manifest parses (staleness reported, not self-test-fatal)")
    return 0 if not failures else 1


def main():
    ap = argparse.ArgumentParser(description="Reconcile the claude.ai knowledge-manifest with its SOURCE files (read-only).")
    ap.add_argument("manifest", nargs="?", default=_MANIFEST, help="path to knowledge-manifest.md")
    ap.add_argument("--real", action="store_true",
                    help="report drift against the committed manifest (exit non-zero on drift); NOT wired into the gate")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return _self_test()
    n, drifts = check(a.manifest)
    for x in drifts:
        _emit("DRIFT " + x)
    _emit("claude.ai pack manifest: %d row(s) checked, %d drift(s)" % (n, len(drifts)))
    if drifts and not a.real:
        _emit("note: rebuild with scripts/build_claude_ai_project_pack.py to refresh the manifest, then re-check.")
    return 0 if not drifts else 1


if __name__ == "__main__":
    sys.exit(main())
